=== Nullstellen mehrdimensionaler Polynome

Zum ermitteln von Nullstellen eines Polynoms, können wir mehrere Methoden verwenden.
Dabei entweder eine Nullstelle bekannt sein, die Funktion Normiert werden oder gleich Null gesetzt werden.

Symetrische Polynome der Form: (stem:[a_2x^2+a_1x+a_0]) könenn wir mit der PQ-Formel auflösen.

PQ-Formel:
[stem]
++++
ax^2 + px + q

x_(1,2)= - p/2 +- sqrt(p^2/2 - q)
++++

Alle anderen Symetrische Polynome der Form: stem:[sum_(i=0)^n a_i*x^i]

müssen wir zunächst auf ein Quadratisches Format bringen. Dazu können wir die gesamte Funktion Häufig mit einem x^n dividieren, so dass stem:[2 = k-n," " k,n in NN]

Dies können wir u.a. durch Substitution erreichen.

[stem]
++++
f(x) = x^4+6x^3+2x^2+6x+1

"Wir wollen nach 0 Lösen"

0 = x^4+6x^3+2x^2+6x+1

"Wir dividieren die Gleichung durch x^2 um eine Quadratische Gleichung zu erhalten.
der Höhste Grad ist ausschlaggebend. Wir erhalten:"

0 = x^4/x^2+6x^3/x^2+2x^2/x^2+6x/x^2+1/x^2

0 = x^2+6x+2+6/x+1/x^2

0 = (x^2+1/x^2)+(6x+6/x)+2

0 = (x+1/x)^2+6(x+1/x)+2

"Wir können "z " für " x+1/x " einsetzen."

sei z = x+1/x

f(z) = z^2+6z+2

z_(1,2) =-3+-sqrt(3^2-2) = -3+-sqrt(7)

z = x+1/x

zx = x^2+1

0 = x^2 -zx + 1

x_(1,2) = -(-3+sqrt(7))/2 +-sqrt((3+sqrt(7))^2/2 - 1)

x_(3,4) = -(-3-sqrt(7))/2 +-sqrt((3-sqrt(7))^2/2 - 1)  " kein Ergebnis da" ( (-3-sqrt(7))^2/2-1 " negativ")

"wir haben 2 Lösungen für Nullstellen bei " x_(1,2) = -(-3+sqrt(7))/2 +-sqrt((3+sqrt(7))^2/2 - 1)

++++

==== Nullstellen von mehrdimensionalen Polynomen mit geraden Graden

Bei geraden Graden können wir i.d.R. stem:[x^n, n = 2k, k in NN] mit z Substituieren.
Nehmen wir zum Beispiel die Funktion stem:[f(x)= x^4+3x^2+2 ] hier kann stem:[x^2] mit z Substituiert werden. Nullstellen der Substituierten Funktion mittels PQ-Formel ermittelt werden.

[stem]
++++
f(x)= x^4+3x^2+2

"sei " z = x^2

f(z) = z^2 + 3z + 2

x_(1,2) = -3/2 +- sqrt(3^2/2 - 2) = -3/2 +- sqrt(5/4) = (-3+-sqrt(5))/2

x_(1,2) = +-sqrt((-3+sqrt(5))/2)

x_(3,4) = +-sqrt((-3-sqrt(5))/2)
++++



Wenn eine Nullstelle bekannt ist, können wir die restlichen
Nullstellen mittels link:Nullstellen/Hornerschema.adoc[Hornerschema]
oder link:Nullstellen/Polynom_division.adoc[Polynomdivision] ermitteln` ermitteln.

include::Nullstellen/Polynom_division.adoc[leveloffset=1]
include::Nullstellen/Hornerschema.adoc[leveloffset=1]