=== Relation und Funktionen
:stem:

Relationen sind alle Abbildungen der Bildmenge auf den Wertebereich.
Nur *linkstotale* und *rechts eindeutige* Abbildungen bezeichnen wir als Funktion.

Aber was bedeutet das eigentlich?

- Linkstotal: stem:[AA a in A] stem:[EE b in B: (a;b) in RR].
Jedem Wert der Bildmenge ist ein Wert im Wertebereich zu geordnet.

- Rechtseindeutig: stem:[AAa in A] stem:[AAb,c in B: (a;b) in RR ^^ (a;c) in RR => b=c].
Für jeden Wert aus dem Wertebereich gibt es genau einen Wert in der Zielmenge.

Ist keine Definitionsmenge angegeben gilt allgemein, dass die Bildmenge den Definitionsbereich darstellt.
Ist kein Wertebereich angegeben ist der Definitionsbereich der Bildmenge anzunehmen.

Beispiel:

Wollen von stem:[f:A->B] abbilden.
Dann ist ohne weitere Angaben der größt mögliche Definitionsbereich für stem:[A] anzunehmen.
Somit ist unsere Bildmenge stem:[RR], analog dazu gilt das selbe für stem:[B], sprich unsere Zielmenge.

include::Relationen/Injektiv.adoc[leveloffset=1]
include::Relationen/Surjektiv.adoc[leveloffset=1]
include::Relationen/Bijektiv.adoc[leveloffset=1]
